### ISSUE TITLE
delegate will panic

### ISSUE THREAD

**Issue by Sherlock-Holo** [passcod/cni-plugins#8]
```rust
debug!("copying bytes={} to stdin", stdin_bytes.len());
let written = copy_buf(&mut stdin_bytes, &mut stdin).await?;
assert_eq!(written as usize, stdin_bytes.len());
```

it will panic at the assert

after copy to the buf, the &[u8] `stdin_bytes` will become a new &[u8], an empty slice

**Comment by passcod** [comment]
Context: in the tokio variant, https://github.com/passcod/cni-plugins/blob/77054fd4186a1f782d8bdef934968c54c6496b03/plugin/src/delegation.rs#L214
