### ISSUE TITLE
some plugin stdoutis empty

### ISSUE THREAD

**Issue by Sherlock-Holo** [passcod/cni-plugins#9]
when call del for host-local, it seems will return nothing through stdout, no matter success or failed

for example, allocate an ip throught `echo '{ "cniVersion": "0.3.1", "name": "examplenet", "ipam": { "type": "host-local", "ranges": [ [{"subnet": "203.0.113.0/24"}], [{"subnet": "2001:db8:1::/64"}]], "dataDir": "/tmp/cni-example"  } }' | CNI_COMMAND=ADD CNI_CONTAINERID=example1 CNI_NETNS=/dev/null CNI_IFNAME=dummy0 CNI_PATH=/opt/cni/bin /opt/cni/bin/host-local`
it will return 
```
{
    "cniVersion": "0.3.1",
    "ips": [
        {
            "version": "4",
            "address": "203.0.113.4/24",
            "gateway": "203.0.113.1"
        },
        {
            "version": "6",
            "address": "2001:db8:1::4/64",
            "gateway": "2001:db8:1::1"
        }
    ],
    "dns": {}
}
```
then call `echo '{ "cniVersion": "0.3.1", "name": "examplenet", "ipam": { "type": "host-local", "ranges": [ [{"subnet": "203.0.113.0/24"}], [{"subnet": "2001:db8:1::/64"}]], "dataDir": "/tmp/cni-example"  } }' | CNI_COMMAND=DEL CNI_CONTAINERID=example1 CNI_NETNS=/dev/null CNI_IFNAME=dummy0 CNI_PATH=/opt/cni/bin /opt/cni/bin/host-local`

it return nothing.

but this crate will panic
```
INFO  cni_plugin::delegation > delegate plugin at /opt/cni/bin/host-local for command=DEL has returned with exit status: 0; stdout bytes=0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Delegated { plugin: "host-local", err: MissingOutput }', /root/native-git/rust/my_cni/src/lib.rs:459:14
```

**Comment by passcod** [comment]
As per [spec](https://github.com/containernetworking/cni/blob/master/SPEC.md#section-4-plugin-delegation):

> Success is indicated by a zero return code and a `Success` result type output to stdout.

If there's no output there's no `Success` result type on output... I'd say that's a `host-local` bug then.

That said, you can handle the delegation error and special-case on `MissingOutput`, pretending that's a success.

**Comment by passcod** [comment]
Closing due to repo archival
